config/routes.rb
Cachely::Application.routes.draw do

  resources :users
  resources :training_sessions
  
  resources :site_training_sessions do
    collection do
      get :order
      post :sort
    end
  end
  
  resources :sessions
  resources :viewers
  resources :viewings
  resources :comments
  resources :sites do
    resource :style_settings
    resource :site_content
  end

  resources :style_settings
  resources :site_contents
  
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"
  match "training_library" => "training_sessions#index"
  
  root to: 'site_training_sessions#index'
  

end

app/models/site_training_session.rb
class SiteTrainingSession < ActiveRecord::Base
  attr_accessible :site_id, :training_session_id, :position
  
  belongs_to :site
  belongs_to :training_session
  
end

app/controllers/site_training_sessions_controller.rb
class SiteTrainingSessionsController < ApplicationController
  authorize_resource
  
  before_filter :viewer_required, :only => [:index]
  
  def index
    if params[:order] == "desc"
      @training_sessions = current_site.training_sessions.order("created_at DESC").page(params[:page]).per_page(25)
    elsif params[:order] == "asc"
      @training_sessions = current_site.training_sessions.order("created_at ASC").page(params[:page]).per_page(25)
    else
      @training_sessions = current_site.training_sessions.order("site_training_sessions.position ASC").page(params[:page]).per_page(25)
    end
  end
  
  def create
    @site_training_session = SiteTrainingSession.new(params[:site_training_session])
    @site_training_session.site_id = current_site.id
    @site_training_session.save
    respond_to do |format|
      format.html { redirect_to site_training_sessions_path,
                    :notice => "Training session published successfully" }
      format.js
    end
  end
  
  def destroy
    @site_training_session = SiteTrainingSession.find_by_training_session_id_and_site_id(params[:site_training_session][:training_session_id], params[:site_training_session][:site_id])
    @site_training_session.destroy
    respond_to do |format|
      format.html { redirect_to site_training_sessions_path,
                    :notice => "Training session unpublished successfully" }
      format.js
    end
  end
  
  def order
    @site_training_sessions = current_site.training_sessions.order("site_training_sessions.position ASC")
  end
  
  def sort
    params[:training_session].each_with_index do |id, index|
      SiteTrainingSession.update_all({position: index+1}, {training_session_id: id, site_id: current_site.id})
    end
    flash[:notice] = "Training sessions reordered successfully"
    render nothing: true
  end
  
  private
  
  def viewer_required
    unless current_user.admin?
      redirect_to new_viewer_url if current_viewer.nil?
    end
  end
  
end

app/views/site_training_sessions/_add_to_site.html.erb
<%= form_for SiteTrainingSession.new, :html => { :class => 'inline' } do |f| %>
  <%= f.hidden_field :training_session_id, :value => training_session_id %>
  <%= f.hidden_field :site_id, :value  => current_site.id %>
  <%= f.submit "Publish", :class => "btn" %>
<% end %>

app/views/site_training_sessions/_remove_from_site.html.erb
<%= form_for SiteTrainingSession.find_by_training_session_id(training_session_id),
    :html => { :method => :delete,  :class => 'inline' } do |f| %>
    <%= f.hidden_field :training_session_id, :value => training_session_id %>
    <%= f.hidden_field :site_id, :value  => current_site.id %>
  <%= f.submit "Unpublish", :class => "btn" %>
<% end %>

app/views/site_training_sessions/index.html.erb
<div class="heading">
  <% if current_user.admin? %>
    <h1>Published Training Sessions</h1>
  <% else %>
    <h1>All Training Sessions</h1>
  <% end%>
  <hr>
  <% if current_user.admin? %>
    <div class="well">
      The training sessions listed below are visible to users of the current site. Click "Unpublish" to remove a training session. You can publish additional training sessions to the current site from the "Training Library". Click "Edit Order" to change the order in which the training sessions are displayed.
    </div>
  <% end %>
</div>

<% if current_viewer %>
  <div id="instructions" class="well">
    <h4>Hi <%= current_viewer.name.capitalize %>,</h4>
    <% if current_site.site_content.training_session_greeting.present? %>
      <p><%= raw current_site.site_content.training_session_greeting %></p>
    <% else%>
      <p>Click on one of the “Select“ buttons below to open a specific training topic. Enter the full names of any other individuals participating in this training session other than yourself (if it’s only you, please leave this field blank) then click on the “Submit Sign-in Sheet” button. A copy of the supplemental PDF documentation will be sent to your email address; you may also open and save the PDF from this page. When ready for the video to begin click the “View Video” button. Use the “HD” and arrow icons on the bottom right of the video to improve the picture quality and expand the video to full-screen. After minimizing the video, you can submit feedback if you’d like (such as comments and questions). Thanks for participating!</p>
    <% end %>
  </div>
<% end %> 

<div class="heading">
  <h3>Currently Available Topics</h3>
  <% if current_user.admin? %>
    <%= link_to 'Edit Order', order_site_training_sessions_path, :class => "action" %>
  <% end %>
  <% if params[:order] == "desc" %>
    <%= link_to 'Oldest first', site_training_sessions_path(:order => 'asc'), :class => "action" %>
  <% else %>
    <%= link_to 'Newest first', site_training_sessions_path(:order => 'desc'), :class => "action" %>
  <% end %>
</div>

<div id="training_sessions">
  <% if @training_sessions.any? %>  
    <% @training_sessions.each_with_index do |training_session, index| %>
      <%= render :partial => training_session, :locals => { :index => index } %>
    <% end %>
  <% else %>
    <p>Nothing to show</p>
  <% end %>
</div>

app/views/site_training_sessions/order.html.erb
<div class="heading">
  <h1>Reorder Training Sessions</h1>
  <p class="muted">Drag and drop training sessions to reorder, then click "done".</p>
  <hr>
</div>
<div id="order_training_sessions">
  <ul id="training_sessions" data-update-url="<%= sort_site_training_sessions_url %>">
  <% @site_training_sessions.each do |training_session| %>
    <%= content_tag_for :li, training_session do %>
      <span class="handle">[drag]</span>
      <%= link_to h(training_session.name), training_session %>
    <% end %>
  <% end %>
  </ul>
  
  <div class="actions">
    <%= link_to "Done", site_training_sessions_url, :class => "btn" %>
  </div>
</div>