config/routes.rb
Cachely::Application.routes.draw do

  resources :users
  resources :training_sessions
  
  resources :site_training_sessions do
    collection do
      get :order
      post :sort
    end
  end
  
  resources :sessions
  resources :viewers
  resources :viewings
  resources :comments
  resources :sites do
    resource :style_settings
    resource :site_content
  end

  resources :style_settings
  resources :site_contents
  
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"
  match "training_library" => "training_sessions#index"
  
  root to: 'site_training_sessions#index'
  

end

app/models/training_session.rb
class TrainingSession < ActiveRecord::Base
  attr_accessible :name, :user_id, :pdf, :vimeo_embed, :site_ids

  mount_uploader :pdf, PdfUploader

  belongs_to :user

  has_many :viewings, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  has_many :site_training_sessions
  has_many :sites, :through => :site_training_sessions
  
  validates :name, :presence => true
  validates :user_id, :presence => true
  validates :vimeo_embed, :presence => true
  
  def pdf_name
    self.pdf.to_s.split("/").last
  end
  
  def completed_by?(viewer)
    viewings.where("viewings.training_session_id = ? 
                    AND viewings.viewer_id = ? 
                    AND viewings.completed_at IS NOT NULL",
                    self.id, viewer.id).any?
  end
end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  include SitesHelper
  authorize_resource
  
  before_filter :viewing_required, :only => [:show]
  
  def index
    if params[:order] == "asc"
      @training_sessions = TrainingSession.order("created_at ASC")
    else
      @training_sessions = TrainingSession.order("created_at DESC")
    end
    @training_sessions = @training_sessions.page(params[:page]).per_page(25)
    authorize! :manage, @training_sessions
  end
  
  def show
    @training_session = TrainingSession.find(params[:id])
    site_can_view?(@training_session)
    if params[:viewing_id].present?
      @viewing = Viewing.find(params[:viewing_id])
    end
    @viewings = @training_session.viewings.order('id DESC').page(params[:page]).per_page(10)
    @comments = @training_session.comments.order('id DESC').page(params[:page]).per_page(5)
    @comment = Comment.new
  end

  def new
    @training_session = TrainingSession.new
  end
  
  def edit
    @training_session = TrainingSession.find(params[:id])
  end
  
  def update
    @training_session = TrainingSession.find(params[:id])
    @training_session.update_attributes(params[:training_session])
    @training_session.save
    redirect_to @training_session, :notice => "Your training session has been successfully updated"
  end

  def create
    @training_session = TrainingSession.new(params[:training_session])
    @training_session.user_id = current_user.id
    if @training_session.save
      redirect_to @training_session, :notice => "Your training session has been successfully created"
    else
      render 'new'
    end
  end

  def destroy
    @training_session = TrainingSession.find(params[:id])
    @training_session.destroy
    flash[:notice] = "Your training session has been successfully deleted"
    redirect_to training_library_path
  end
  
  private
  
  def viewing_required
    unless current_user.admin?
      redirect_to(root_url, :notice => "Choose a training session to begin a viewing") unless params[:viewing_id]
    end
  end
  
end

app/views/training_sessions/_form.html.erb
<%= form_for @training_session, :html => { :multipart => :true } do |f| %>
  
  <% if @training_session.errors.any? %>
    <h3 class="danger">Please correct the following <%= 'error'.pluralize(@training_session.errors.count) %>:</h3>
    <% @training_session.errors.full_messages.each do |error| %>
      <p class="danger"><%= error %></p>
    <% end %>
    <br>
  <% end %>
  
  <div class="control-group">
    <%= f.label :name, "Training Session Name", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :vimeo_embed, "Vimeo Video ID", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :vimeo_embed %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :pdf, "PDF", :class => "control-label" %>
    <% if @training_session.pdf.present? %>
      <p class="muted"><%= @training_session.pdf_name %></p>
    <% end %>
    <div class="controls">
      <%= f.file_field :pdf %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :site_ids, "Sites", :class => "control-label" %>
    <div class="controls">
          <%= f.collection_select :site_ids, 
                                  Site.order(:name => "ASC"), 
                                  :id, :name, {}, { multiple: true } 
                                  %>
        </div>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
   
<% end %>

app/views/training_sessions/_training_session.html.erb
<div class="training_session">
  <hr>
  <div class="media">
    <div class="media-body">
      <h3 class="media-heading">
        <% if current_user.admin? %>
          <%= link_to "#{index + 1}. #{training_session.name}", training_session %>
        <% else %>  
          <%= link_to "#{index + 1}. #{training_session.name}", new_viewing_path(:training_session_id => training_session.id) %>
        <% end %>
        <% if current_viewer && training_session.completed_by?(current_viewer)%>
          <span class="subheading completed"><i class="icon-ok"> Completed</i></span>
        <% end %>
      </h3>
      <p class="muted">
        Added on <%= date_for training_session.created_at %>
      </p>
      <% if current_user.admin? %>
        <p class="muted">
          <% if params[:controller] == "site_training_sessions" %>
            <%= pluralize current_site.viewings_for(training_session).count, 'view' %> |
            <%= pluralize current_site.comments_for(training_session).count, 'comment' %>
          <% else %>
            <%= pluralize training_session.viewings.count, 'view' %> |
            <%= pluralize training_session.comments.count, 'comment' %>
          <% end %>      
        </p>
      <% end %>
      <% if current_user.admin? %>
        <div class="actions pull-right">
          <% if current_site.can_view? training_session %>
            <%= render :partial => "site_training_sessions/remove_from_site",
                       :locals => { :training_session_id => training_session.id } %>
          <% else %>
            <%= render :partial => "site_training_sessions/add_to_site",
                       :locals => { :training_session_id => training_session.id } %>
          <% end %>
          <% if params[:controller] == "training_sessions" %>
            <%= link_to 'Edit', edit_training_session_path(training_session) %>
            <%= link_to 'Delete', training_session, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "danger" %>
          <% end %>
        </div>
      <% end %>
      <% if current_user.admin? %>
        <p><strong><%= link_to 'View Video', training_session %></strong></p>
      <% else %>
        <p><strong><%= link_to 'View Video', new_viewing_path(:training_session_id => training_session.id) %></strong></p>
      <% end %>
    </div>
  </div>
</div>

app/views/training_sessions/_training_sessions.html.erb
<div class="training_session">
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= index + 1 %>. 
        <% if current_user.admin? %>
          <%= link_to training_session.name.titleize, training_session %>
        <% else %>  
          <%= link_to training_session.name.titleize, new_viewing_path(:training_session_id => training_session.id) %>
        <% end %>
      </h4>
      <p><%= date_for training_session.created_at %></p>
      <% if current_user.admin? %>
        <p class="muted">
          <%= pluralize training_session.viewings.count, 'view' %> |
          <%= pluralize training_session.comments.count, 'comment' %>
        </p>
        <div class="actions">
          <%= link_to 'Edit', edit_training_session_path(training_session) %>
          <%= link_to 'Delete', training_session, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "danger" %>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
</div>

app/views/training_sessions/edit.html.erb
<div class="row">
  <div class="span6">
    <div class="heading">
      <h1>Edit Training Session</h1>
      <hr>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/training_sessions/index.html.erb
<div class="heading">
  <h1>Training Session Library</h1>
  <hr>
  <div class="well">
    The training session library is where you manage your training sessions. Click "Add A Topic" to create a new training session. Click "Publish" to publish a training session. Published training sessions will made available to all users of the current site.
  </div>
  <% if current_user.admin? %>
    <%= link_to 'Add A Topic', new_training_session_path, :class => "btn btn-large btn-success" %>
  <% end %> 
  <% if params[:order] == "desc" %>
    <%= link_to 'Oldest first', training_library_path(:order => 'asc'), :class => "action" %>
  <% else %>
    <%= link_to 'Newest first', training_library_path(:order => 'desc'), :class => "action" %>
  <% end %>
</div>

<div id="training_sessions">
  <% if @training_sessions.any? %>  
    <% @training_sessions.each_with_index do |training_session, index| %>
      <%= render :partial => training_session, :locals => { :index => index } %>
    <% end %>
  <% else %>
    <div class="heading">
      <p>Nothing to show</p>
    </div>
  <% end %>
  <%= will_paginate @training_sessions %>
</div>

app/views/training_sessions/new.html.erb
<div class="row">
  <div class="span6">
    <div class="heading">
      <h1>New Training Session</h1>
      <hr>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/training_sessions/order.html.erb
<div class="heading">
  <h1>Sort Training Sessions</h1>
  <p class="muted">Drag and drop training sessions to reorder, then click "done".</p>
  <hr>
</div>
<div id="order_training_sessions">
  <ul id="training_sessions" data-update-url="<%= sort_training_sessions_url %>">
  <% @training_sessions.each do |training_session| %>
    <%= content_tag_for :li, training_session do %>
      <span class="handle">[drag]</span>
      <%= link_to h(training_session.name), training_session %>
    <% end %>
  <% end %>
  </ul>
  
  <div class="actions">
    <%= link_to "Done", training_sessions_url, :class => "btn" %>
  </div>
</div>

app/views/training_sessions/show.html.erb
<div id="training_session" class="row">
  <% if @training_session.vimeo_embed.present? %>
    <%= render :template => 'training_sessions/vimeo_embed', :locals => { :vimeo_embed => @training_session.vimeo_embed } %>
  <% else %>
    <div class="span12">
      <p>Sorry, but no video is currently available for this training session. Please try again later.</p>
    </div>
  <% end %>
</div>

<br>

<div class="heading">
  <p class="muted"><strong>Trouble viewing this video?</strong> IE8 users please make sure <%= link_to "Adobe Flash Player", "https://get.adobe.com/flashplayer/" %> is installed and up to date.</p>  
  <h2><%= @training_session.name %></h2> 
  <% if @training_session.pdf.present? %>
    <p><%= link_to "View PDF", @training_session.pdf_url, :class => "link-large" %></p>
  <% end %> 
  <% if current_user.admin? %>
    <div class="actions">
      <%= link_to "Edit", edit_training_session_path(@training_session) %>
      <%= link_to "Delete", @training_session, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "danger" %>
    </div>
  <% end %>
  <hr>
</div>

<div id="comments">
  <% if current_viewer %>
    <div class="heading">
      <h3>Leave a comment <span class="muted" style="font-size:large; font-weight:normal">(Optional)</span></h3>
    </div>
    <%= form_for @comment do |f| %>
      <%= f.hidden_field :training_session_id, :value => @training_session.id %>
      <%= f.hidden_field :viewing_id, :value => @viewing.id %>
      <%= f.hidden_field :viewer_id, :value => current_viewer.id %>
      <%= f.hidden_field :site_id, :value => current_site.id %>
      <div class="control-group">
        <div class="controls">
          <%= f.text_area :content, :class => "span10", :rows => 3 %>
        </div>
      </div>
      <p class="hint"><i class="icon-ok"></i>
        Click done to complete this training session.</p>
      <%= f.submit "Done", :class => 'btn btn-large btn-success' %>
    <% end %>
  <% else %>
    <div class="heading">
      <h3>Comments</h3>
    </div>
    <% if @comments.any? %>
      <%= render @comments%>
    <% else %>
    <div class="comment">
      <p>No comments to show.</p>
    </div>
    <% end %>
  <% end %>
</div>

<% if current_user.admin? %>
  <div id="viewings">
    <hr>
    <h3>Viewing Log</h3>
    <p class="muted"><%= @training_session.name %> has been viewed <%= pluralize @viewings.count, 'time' %></p>
    <br>
    <% if @viewings.any? %>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Viewing Date</th>
            <th>Viewer Name</th>
            <th>Site Name</th>
            <th>Participants</th>
            <th>Completed?</th>
          </tr>
        </thead>
        <tbody>
          <%= render @viewings %>
        </tbody>
      </table>
    <% else %>
      <p>Nothing to show.</p>
    <% end %>
    <%= will_paginate @viewings, :params => { :anchor => "viewings" } %>
    <br>
    <p><%= link_to raw("&#8592; Return to training sessions"), site_training_sessions_path, :class => 'link-large' %></p>
    <br>
  </div>
<% end %>

app/views/training_sessions/vimeo_embed.html.erb
<div class="vimeo_embed">
  <script type="text/javascript">
    function hideProgress(){ document.getElementById('loader').style.display = 'none'; }
  </script>
  <div id="loader" class="muted" style="padding-left:20px">Please wait for the video to load...</div>
  <iframe width="907px" height="480px" src="https://player.vimeo.com/video/<%= vimeo_embed %>" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen onload="hideProgress()">  
  </iframe>
</div>