config/routes.rb
Cachely::Application.routes.draw do

  resources :users
  resources :training_sessions
  
  resources :site_training_sessions do
    collection do
      get :order
      post :sort
    end
  end
  
  resources :sessions
  resources :viewers
  resources :viewings
  resources :comments
  resources :sites do
    resource :style_settings
    resource :site_content
  end

  resources :style_settings
  resources :site_contents
  
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"
  match "training_library" => "training_sessions#index"
  
  root to: 'site_training_sessions#index'
  

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :name, :subdomain, :banner_image
  
  has_one :style_setting, :dependent => :destroy
  has_one :site_content, :dependent => :destroy
  
  has_many :users
  has_many :site_training_sessions
  has_many :training_sessions, :through => :site_training_sessions
  has_many :viewings
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  validates_presence_of :subdomain
  validates_uniqueness_of :subdomain
  validates_format_of :subdomain, :with => /^[a-z\d]+(-[a-z\d]+)*$/i
  
  mount_uploader :banner_image, ImageUploader
  
  def can_view?(training_session)
    site_training_sessions.where(:site_id => self.id, :training_session_id => training_session.id).any?
  end
  
  def banner_image_name
    self.banner_image.to_s.split("/").last
  end
  
  def viewings_for(training_session)
    training_session.viewings.joins(:site).where("viewings.site_id = ?", self.id)
  end
  
  def comments_for(training_session)
    training_session.comments.joins(:site).where("comments.site_id = ?", self.id)
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  authorize_resource
  include SitesHelper
  
  def index
    @sites = Site.order("name ASC").page(params[:page]).per_page(50)
  end
  
  def new
    @site = Site.new
  end

  def create
    @site = Site.new(params[:site])
    if @site.save
      @site.create_style_setting!
      @site.create_site_content!
      redirect_to sites_path, :notice => "Site was successfully created"
    else
      render :action => 'new'
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update_attributes(params[:site])
      redirect_to @site, :notice => "Site was successfully updated"
    else
      render :action => 'edit'
    end
  end
  
  def show
    @site = Site.find(params[:id])
  end
  
  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path, :notice => "Site was successfully deleted"
  end
  
end

app/helpers/sites_helper.rb
module SitesHelper
  def domain_name_for(site)
    "#{request.protocol}#{site.subdomain}.#{request.domain}"
  end
  
  def site_can_view?(training_session)
    unless (current_site.can_view?(training_session) || current_user.admin?)
      redirect_to(root_url, :alert => "You are not authorized to access this page.")
    end 
  end
end

app/views/sites/_form.html.erb
<%= form_for @site do |f| %>
  <div class="well">
    When setting up a new site, keep in mind someone in IT will need to create a DNS record for your preferred domain name before clients will be able to reach it.
  </div>

  <% if @site.errors.any? %>
    <h3 class="danger">Please correct the following <%= 'error'.pluralize(@site.errors.count) %>:</h3>
    <% @site.errors.full_messages.each do |error| %>
      <p class="danger"><%= error %></p>
    <% end %>
    <br>
  <% end %>

    <div class="control-group">
      <%= f.label :name, "Site Name", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name, :placeholder => "Site Name", :autocomplete => "off" %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :subdomain, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :subdomain, :placeholder => "Subdomain" %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :banner_image, "Banner Image", :class => "control-label" %>
      <% if @site.banner_image.present? %>
        <p class="muted"><%= @site.banner_image_name %></p>
      <% end %>
      <div class="controls">
        <%= f.file_field :banner_image %>
      </div>
    </div>
    
    <div class="actions">
      <%= f.submit :class => 'btn' %>
    </div>
  
<% end %>

app/views/sites/_site.html.erb
<div class="row">
  <div class="site span12">
    <hr>
    <h3><%= link_to site.name, site %></h3>
    <h4><%= link_to "#{domain_name_for(site)}", "#{domain_name_for(site)}" %></h4>
    <p class="muted">Created on <%= site.created_at.strftime("%A, %b %-d %Y,%l:%M %p") %></p>
    <p class="muted">
      <%= pluralize site.users.count, 'user' %> |
      <%= pluralize site.viewings.count, 'training session' %> viewed |
      <%= pluralize site.training_sessions.count, 'published training session' %>
    </p>
    <% if current_user.admin? %>
      <div class="actions pull-right">
        <%= link_to "Edit", edit_site_path(site) %>
        <%= link_to "Delete", site, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "danger" %>
      </div>
    <% end %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/sites/edit.html.erb
<div class="heading">
  <h1>Edit Site</h1>
  <hr>
</div>
<div class="row">
  <div class="span6">
    <%= render 'form' %>
  </div>
</div>

app/views/sites/index.html.erb
<div class="heading">
  <h1>All Sites</h1>
  <hr>
  <div class="well">
    Sites are used to determine what users see what training sessions. Sites can also be used to customize content and look and feel. You can access these settings by choosing a site, clicking on "Edit Style Settings" or "Edit Content".
  </div>
  <p><%= link_to "Add a site", new_site_path, :class => "btn btn-large btn-success" %></p>
</div>
<div id="sites">
  <%= render @sites %>
</div>
<%= will_paginate @sites %>

app/views/sites/new.html.erb
<div class="heading">
  <h1>New Site</h1>
  <hr>
</div>
<div class="row">
  <div class="span6">
    <%= render 'form' %>
  </div>
</div>

app/views/sites/show.html.erb
<div class="row">
  <div class="span12">
    <div class="heading">
      <h1><%= @site.name %></h1>
      <h4><%= link_to "#{domain_name_for(@site)}", "#{domain_name_for(@site)}" %></h4>
      <% if current_user.admin? %>
        <div class="actions">
          <%= link_to "Edit Site", edit_site_path(@site) %>
          <%= link_to "Edit Style Settings", edit_site_style_settings_path(@site) %>
          <%= link_to "Edit Content", edit_site_site_content_path(@site) %>
          <%= link_to "Delete", @site, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "danger" %>
        </div>
      <% end %>
      <div class="clearfix"></div>
    </div>
    <% if @site.users.any? %>
      <div class="heading">
        <hr>
        <h2>User List</h2>
      </div>
      <div id="users">
        <%= render @site.users %>
      </div>
    <% end %>
  </div>
</div>