config/routes.rb
Cachely::Application.routes.draw do

  resources :users
  resources :training_sessions
  
  resources :site_training_sessions do
    collection do
      get :order
      post :sort
    end
  end
  
  resources :sessions
  resources :viewers
  resources :viewings
  resources :comments
  resources :sites do
    resource :style_settings
    resource :site_content
  end

  resources :style_settings
  resources :site_contents
  
  match "login" => "sessions#new"
  match "signout" => "sessions#destroy"
  match "training_library" => "training_sessions#index"
  
  root to: 'site_training_sessions#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= current_site.name %> Training</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <% unless params[:controller] == "style_settings" && params[:action] == "update" %>
    <%= render :template => "layouts/site_styles", :locals => { :style_setting => current_site.style_setting } %>
  <% end %>
</head>
<body>
  <div class="container">
    <% if current_site.banner_image.present? %>
      <div id="banner"></div>
    <% else %>
      <br>
      <div class="heading">
        <h1><%= current_site.name %> Training</h1>
      </div>
    <% end %>
  </div>
  <div id="content" class="container">
      <div class="row">
        <div class="span12">
          <% if logged_in? && current_user.admin? %>
            <div class="navbar">
              <div class="navbar-inner">
                <ul class="nav">
                  <li><%= link_to "Published Training Sessions", site_training_sessions_path %></li>
                  <li><%= link_to "Training Library", training_library_path %></li>
                  <li><%= link_to "Viewing Log", viewings_path %></li>
                  <li><%= link_to "User List", users_path %></li>
                  <li><%= link_to "Site List", sites_path %></li>
                  <li><%= link_to "Sign out", signout_path %></li>
                </ul>
              </div>
            </div>
          <% elsif logged_in? %>
            <div class="nav actions pull-right">
              <% if current_viewer %>
                <span class="action">Signed in as <%= link_to current_viewer.name.capitalize, current_viewer %></span> 
                <span class="muted">Not you?</span> 
              <% end %>
              <span class="action">
                <%= link_to "Sign out", signout_path, :class => "signout_link" %>
              </span>
          </div>
          <% end %>
        </div>
      </div>
      <% if flash.any? %>
        <% flash.each do |name, msg| %>
          <div class="row">
              <div class="span12">
              <div class="alert alert-<%= name %>">
                <%= msg %>
                <div id="alert-dismiss" class="muted pull-right">
                  <i class="icon-remove"></i>
                </div>
              </div> 
            </div>
          </div>
        <% end %>
      <% end %>
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= render :template => 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/footer.html.erb
<div id="footer">
  <% if current_site.site_content.footer_text.present? %>
  <div class="row">
    <div class="span12 footer-top">
	    <div class="daas-logo pull-left">
	    	<a href="#" title="Department of Aging and Adult Services">
	    		<img src="/assets/daas.png" alt="Department of Aging and Adult Services">
	    	</a>
	    </div>
	    <div class="footer-text">
	    	 <%= current_site.site_content.footer_text %>
	    </div>
	    <div class="clearfix"></div>
	  </div>
	</div>
	<% end %>
	<div class="row">
	  <div class="footer-bottom" role="about us">
	  	<div class="span4 pull-left">
	  		Copyright © 2013 All rights reserved.
	  	</div>
	  	<div class="span1 pull-left">
	  		<a href="http://rtzassociates.com/" title="about us">About Us</a>
	  	</div>
	  	<div class="span1 pull-left">
	  		<a href="#" title="contact">Contact</a>
	  	</div>
	  	<div class="span1 pull-left">
	  	  <a href="#" title="privacy">Privacy</a>
	  	</div>
	  	<div class="span4 pull-right">
	  		 Powered by <a href="http://rtzassociates.com/" title="RTZ Associates">RTZ</a>
	  	</div>
	  	<div class="clearfix"></div>
	  </div>
</div>

app/views/layouts/site_styles.html.erb
<style type="text/css">
  body {
    background-color: <%= style_setting.body_background_color %>;
  }   
  #footer {
    background-color: <%= style_setting.footer_background_color %>;
    color: <%= style_setting.footer_text_color %>;
  }   
  a {
    color: <%= style_setting.link_color %>;
  }
  #banner {
    min-height: <%= current_site.banner_image.height %>px;
    margin-bottom: 1em;
    background-image-width: 940px;
    background-image: url("<%= current_site.banner_image_url %>");
    background-repeat: no-repeat;
  }
</style>